name: Déploiement GitHub Pages

on:
  push:
    branches: ['main', 'master']
  workflow_dispatch:

# Autorisations nécessaires pour GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permet d'éviter les déploiements simultanés
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code (Checkout)
        uses: actions/checkout@v4

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Installation des dépendances
        run: npm ci

      - name: Compilation Vite (Site statique)
        run: npm run build:static

      - name: Configuration de GitHub Pages
        uses: actions/configure-pages@v5

      - name: Téléversement de l'artefact (dossier dist)
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Déploiement sur GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
